- name: Get SLDs from website URLs
  set_fact:
    slds: "{{ slds|default([]) + [ item.value.bare_url | regex_search('(?:.+\\.)?([^.]+\\.(?:com|org|net|coop|space|co.uk|edu|info|us))', '\\1') | first ] }}"
  when: item.value.env != 'Test'
  loop: "{{ sites|default({})|dict2items }}"

- name: Get SLD from the server FQDN
  set_fact:
    server_slds:
      - "{{ fqdn | regex_search('(?:.+\\.)?([^.]+\\.(?:com|org|net|coop|space|co.uk|edu|info|us))', '\\1') | first}}"

- name: combine domain and server SLDs + default DMARC domains to omit
  set_fact:
    slds: "{{ slds|default([]) | union(server_slds) }}"
    dmarc_domains_to_omit: "{{ dmarc_domains_to_omit|default('', true) }}"

- name: Set any additional SLDs
  set_fact:
    slds: "{{ slds + second_level_domains.split(', ') | unique }}"
  when: second_level_domains is defined

- name: Set dmarc_domains
  set_fact:
    dmarc_domains: "{{ slds | difference(dmarc_domains_to_omit.split(', ')) }}"

- name: Create a host file on the primary Icinga
  template:
    src: "{{ template_src }}"
    dest: /etc/icinga2/zones.d/master/hosts/{{ fqdn }}.conf
  delegate_to: "{{ primary_icinga_server }}"
  notify: restart primary icinga
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
